sudo: false

language: php

cache:
  directories:
  - $HOME/.composer/cache

services:
- redis-server

env:
  global:
  - COMPOSER_ARGS="--no-interaction"
  - TESTS_ZEND_CACHE_REDIS_ENABLED=true
  - TESTS_ZEND_CACHE_REDIS_HOST="127.0.0.1"
  - TESTS_ZEND_CACHE_REDIS_PORT=6379
  - TESTS_ZEND_CACHE_REDIS_PASSWORD=""
  - TESTS_ZEND_CACHE_REDIS_DATABASE=0

matrix:
  include:
  - php: 7.1
    env:
    - DEPS=lowest
  - php: 7.1
    env:
    - DEPS=locked
    - CS_CHECK=true
  - php: 7.1
    env:
    - DEPS=latest
  - php: 7.2
    env:
    - DEPS=locked
  - php: 7.2
    env:
    - DEPS=latest

install:
- if [[ $TESTS_ZEND_CACHE_REDIS_ENABLED == 'true' ]]; then
  phpenv config-add .ci/redis.ini ;
  fi ;

- travis_retry composer install $COMPOSER_ARGS --ignore-platform-reqs
- if [[ $LEGACY_DEPS != '' ]]; then travis_retry composer update $COMPOSER_ARGS --with-dependencies $LEGACY_DEPS ; fi
- if [[ $DEPS == 'latest' ]]; then travis_retry composer update $COMPOSER_ARGS ; fi
- if [[ $DEPS == 'lowest' ]]; then travis_retry composer update --prefer-lowest --prefer-stable $COMPOSER_ARGS ; fi
- stty cols 120 && composer show

script:
- composer run-script test -- --verbose
- if [[ $CS_CHECK == 'true' ]]; then composer cs-check ; fi


notifications:
  email: false
